### ISSUE TITLE
get_properties should return just one eval point

### ISSUE THREAD

**Issue by longemen3000** [ypaul21/OpenSAFT.jl#10]
thanks to julia broadcasting system, you can do:
```julia
f.(vec) 
```
that evaluates f in a vector `vec`. 
at the moment, for example, `get_volume` returns a vector, but in the rest of equations, just the first element is used
to support this properly, you need to make the EoS broadcastable, this can be done by:
```julia
Base.broadcastable(x::SAFT) = Ref(x)
```

**Comment by longemen3000** [comment]
this also would allow to use the julia threading or distributed systems to evaluate multiple points at once

**Comment by pw0908** [comment]
Hi Andrés,
Thanks a lot for pointing this out! This is indeed a feature we intend to add in OpenSAFT in the near future. For now, we're mainly focusing on adding more equations of state and improving the performance of the solvers.
